apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: my-shopping-app-server
spec:
  # 1 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: shopping-app-server
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: shopping-app-server
    spec:
      containers:
      - name: shopping-app-server
        # Run this image
        image: saurabhwarhade/shoppingappserver:v1.0
      - name : mongodb
        image: mongo:latest