apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: service-my-shopping-app-server
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: shopping-app-server
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer